### ISSUE TITLE
Support for '.inx' files

### ISSUE THREAD

**Issue by lcnittl** [prettier/plugin-xml#111]
This is similar to #89:

Is it possible to add `.inx` files to be recognized by your plugin? `.inx` is an `.xml` file used by Inkscape and Adobe InDesign.

Thanks in advance!

PS: Is there maybe a CLI option or a config file (don't think prettier supports any, right?) that would accept a list of extensions?

**Comment by kddeisz** [comment]
Hey there!

Yeah you can configure prettier. Docs are here: https://prettier.io/docs/en/configuration.html. For something like this, you could use the `overrides` options, as in:

```json
{
  "overrides": [
    {
      "files": "*.foo",
      "options": {
        "parser": "xml"
      }
    }
  ]
}
```

That being said, I've added that extension here (https://github.com/prettier/plugin-xml/commit/8e6a9373700b93ea8b5517f1e043d445ca20cda1) and will release it shortly.

**Comment by bamapookie** [comment]
Thanks for this.  It works for `.drawio` files as well.
