### ISSUE TITLE
Wrong spacing for opening tag with tab ident 2

### ISSUE THREAD

**Issue by ArnaudBarre** [prettier/plugin-xml#114]
Thanks for making this great addition to Prettier!

I tried to use it on my React-Native project, but for an AndroidManifest file I got a strange result:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<manifest
  xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools"
>

    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />

    <application
    android:usesCleartextTraffic="true"
    tools:targetApi="28"
    tools:ignore="GoogleAppIndexingWarning"
  />
</manifest>
```

Context:

- Prettier 2.0.5
- Plugin 0.11.0
- Configuration: `"trailingComma": "all"`

**Comment by kddeisz** [comment]
Thanks for reporting. Can you post the original source file?

**Comment by ArnaudBarre** [comment]
I needed to zip it for GH to accept it:
[AndroidManifest.xml.zip](https://github.com/prettier/plugin-xml/files/5103306/AndroidManifest.xml.zip)

**Comment by kddeisz** [comment]
For android manifests I would suggest `"xmlWhitespaceSensitivity": "ignore"` as I don't think there's significant whitespace in that schema. Right now it's trying to preserve all whitespace, which is why you're seeing this output.

**Comment by ArnaudBarre** [comment]
Is there a lot of xml file that depends on significant whitespace? Because the default is not very friendly (I had the same issue with some SVG files).

**Comment by kddeisz** [comment]
It's a tough call. It completely depends on the schema. Technically, unless folks specify that the whitespace is insignificant, changing the whitespace changes the meaning of the markup. And since prettier has the contract of never changing the meaning of your program, I went with that as the default. That being said, most folks want the behavior to change it. So I'm not sure of the right answer.

**Comment by ArnaudBarre** [comment]
Yes I agree it would break prettier philosophy. Maybe just make it more visible in the documentation that in most cases (svg) this flag should be enabled
