### ISSUE TITLE
Getting "No formatter installed" error when attempting to format with VSCode

### ISSUE THREAD

**Issue by noelforte** [prettier/plugin-xml#130]
**Steps I took:**
1. Installed `vscode-prettier` extension
2. Installed `@prettier/plugin-xml` plugin locally
3. Ran "Format document"
4. Getting this error: 

<img width="461" alt="image" src="https://user-images.githubusercontent.com/2560683/96025522-3aea2600-0e23-11eb-8b3d-cfeee28173cc.png">

Came across https://github.com/prettier/prettier-vscode/issues/1579 in which @ntotten deferred to this plugin to handle XML formatting, just haven't been able to get it running yet.

**Comment by infotexture** [comment]
@noelforte Sounds like the VS Code extension may not be aware that you've installed the XML plugin locally.

Per https://github.com/prettier/prettier-vscode#prettier-resolution, you might want to try setting `prettier.resolveGlobalModules` to `true`, or install it as a dev dependency of the current project:

```
npm install --save-dev prettier @prettier/plugin-xml
```

That will add something like this to the project's `package.json` file:

```json
  "devDependencies": {
    "@prettier/plugin-xml": "0.12.0",
    "prettier": "2.1.2"
  }
```

I chose the latter approach, and it works fine in the projects that I've set up this way. 

If you're running it on an XML file in a folder that hasn't been initialized with a `package.json` file, or the plugin is not yet installed as dev dependency, that would probably explain the error.

**Comment by kddeisz** [comment]
^^^ Thanks @infotexture! This is correct.

@noelforte do you have the plugin as a dev dep?

**Comment by noelforte** [comment]
Installed prettier and prettier-plugin-xml as dev dependencies via

npm install --save-dev prettier @prettier/plugin-xml

Without doing anything else, now getting:

<img width="452" alt="Invalid prettier configuration file detected. See log for details." src="https://user-images.githubusercontent.com/2560683/96390739-07d9c680-1184-11eb-8721-6e83b97934d2.png">.

Prettier seems to work fine with VSCode when not locally installed per project so that's why I had it set up globally.

**Comment by kddeisz** [comment]
I think this might be better taken up with the vscode plugin. This seems more related to that than this specific prettier plugin.

**Comment by noelforte** [comment]
Mmm. Sounds like a plan, thanks for the help @kddeisz!
