### ISSUE TITLE
Add line breaks?

### ISSUE THREAD

**Issue by stephen-last** [prettier/plugin-xml#154]
If I have an xml string like:

```xml
<xml><test myAttr="test123">Test</test></xml>
```

Should this plugin be adding line breaks, like:

```xml
<xml>
  <test myAttr="test123">Test</test>
</xml>
```

If not by default, is there an option for this..?

**Comment by kddeisz** [comment]
Yeah set `xmlWhitespaceSensitivity` to `"ignore"`. By default every node in XML is whitespace-sensitive, so we can't add content in there without semantically breaking it. But if you set it to `"ignore"` then it'll do what you want.
