### ISSUE TITLE
There is a way to keep blank lines?

### ISSUE THREAD

**Issue by nelson6e65** [prettier/plugin-xml#156]
This file

```xml
<phpdoc>
  <title>PHPDoc-VuePress demo</title>

  <files>
    <directory>demo</directory>
    <directory>api</directory>
  </files>
</phpdoc
```

...get removed the black space.
```xml
<phpdoc>
  <title>PHPDoc-VuePress demo</title>
  <files>
    <directory>demo</directory>
    <directory>api</directory>
  </files>
</phpdoc
```

I would like to keep it to improve readability, specially in large files.

Could be nice to have a `maxBlackLines`-like option.

**Comment by kddeisz** [comment]
Yeah. I'm going to do this in #157. I'll collapse them down to 1 blank line if there are multiple, but will respect them.

**Comment by nelson6e65** [comment]
😮
Amazing! Thanks!

**Comment by kddeisz** [comment]
Out in v0.13.0
