### ISSUE TITLE
Allow html tags not to be self-closed

### ISSUE THREAD

**Issue by ramykl** [prettier/plugin-xml#164]
We are using XML as our scaffold for HTML, which means we have things like
```
<div></div>
```
This gets changed to `<div />` which is no longer valid HTML. It would be great to have an option to not self-close these tags

**Comment by kddeisz** [comment]
Unfortunately I do not think this will be possible. Opening the door to parsing HTML would mean that we would need to additionally support the possible void tags and foreignObject tags, both of which would be large additions to the parser. I'd prefer to keep this plugin such that it only supports XML and XML-type documents like SVG and XHTML.

To solve your problem specifically, I'd suggest using prettier's built-in HTML parser.

**Comment by ramykl** [comment]
Thanks. Yeah, just found how to get prettier to use the HTML parser. I did have a weird issue where I needed this plugin to get it to work, although I override the parser to use HTML. Seems a bit strange, but thanks for getting back to me

**Comment by Toliak** [comment]
Hello.
I have the same issue with the raw XML. Unfortunately, some applications are not able to determine self-closed XML tags.
I am going to make a Merge Request with the new property `xmlExpandSelfClosingTags`.
