### ISSUE TITLE
Not converting tabs to spaces

### ISSUE THREAD

**Issue by jahvi** [prettier/plugin-xml#165]
For some reason the module is not converting tabs to spaces when using the `useTabs: false` option, it does work the other way though (spaces to tabs work ok).

**Input** (it's hard to see but indentation is using tabs)
```xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<acl>
		<resources/>
	</acl>
</config>
```

**Expected Result** (spaces instead of tabs)
```xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <acl>
        <resources />
    </acl>
</config>
```

**Actual Result** (still tabs)
```xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<acl>
		<resources />
	</acl>
</config>
```

**.prettierrc**
```
{
    "printWidth": 120,
    "tabWidth": 4,
    "useTabs": false,
    "singleQuote": true
}
```

**Comment by kddeisz** [comment]
If you set `xmlWhitespaceSensitivity` to `"ignore"` what happens? It looks like you're running with the default configuration which is that XML nodes are all whitespace sensitive.

**Comment by jahvi** [comment]
Thanks that does fix the issue.
