### ISSUE TITLE
Option for closing bracket to be on the same line

### ISSUE THREAD

**Issue by jingtang10** [prettier/plugin-xml#171]
## Metadata

- `@prettier/plugin-xml` version: '0.13.0
- Options:

Our gradle spotless config:

```
        format 'xml', {
            target '**/*.xml'
            prettier(['prettier': '2.0.5', '@prettier/plugin-xml': '0.13.0']).config(['parser': 'xml', 'tabWidth': 4])
        }
```
  - `xmlSelfClosingSpace`: true
  - `xmlWhitespaceSensitivity`: `"strict"` (be 100% sure changing this to `"ignore"` doesn't fix your issue)
      - changing it to ignore actually throws an error: `(Error while formatting: TypeError: Cannot read property 'startLine' of undefined)`

## Input

```xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    ...
    android:orientation="horizontal">
```

## Current output

```xml
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    ...
    android:orientation="horizontal"
>
```

## Expected output

```xml
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    ...
    android:orientation="horizontal" >
```

**Comment by kddeisz** [comment]
@jingtang10 v0.13.1 fixes the error you're describing

**Comment by kddeisz** [comment]
You'd expect there to be a space after the last attribute?

**Comment by jingtang10** [comment]
Thanks. Is there a new option being introduced for this in 0.13.1?

I do expect a space after the last attribute but this issue isn't about that. I'm more concerned about the closing bracket on a new line.

**Comment by tomereli** [comment]
I (think) I'm using v0.13.1 and this doesn't seem to be implemented, I still get the XML closing bracket in a new line, which is annoying.
