### ISSUE TITLE
Comments are not preserved

### ISSUE THREAD

**Issue by 70853n** [prettier/plugin-xml#189]
## Metadata

- `@prettier/plugin-xml` version: 0.13.1
- Options:
  - `xmlSelfClosingSpace`: true
  - `xmlWhitespaceSensitivity`: `"ignore"`

## Input

```xml
<parent>
<-- Start children -->
  <child />
  <child />
  <child />
  <child />
<-- End children -->
</parent>

```

## Current output

```xml
<parent>
  <child />
  <child />
  <child />
  <child />
</parent>

```

## Expected output

```xml
<parent>
<-- Start children -->
  <child />
  <child />
  <child />
  <child />
<-- End children -->
</parent>
```

**Comment by kddeisz** [comment]
So that's not valid XML. I'm surprised it's not throwing an error, as it should be. You're missing the `!` at the beginning of the comments, as in:

```xml
<parent>
<!-- Start children -->
  <child />
  <child />
  <child />
  <child />
<!-- End children -->
</parent>
```

**Comment by 70853n** [comment]
Ye my bad for copying it wrong. But the bug is prevalent for me, as proper comments are removed.

**Comment by kddeisz** [comment]
If you include the comments correctly, are they getting removed for you? I haven't seen that behavior.

**Comment by 70853n** [comment]
Sorry for the false alarm. My local setup was flawed. Works as expected (y)

**Comment by acdha** [comment]
In case anyone else encounters this, the ancient `prettier-plugin-xml` will strip comments and attribute values. `@prettier/plugin-xml` is what you want.
