### ISSUE TITLE
Preserve comments

### ISSUE THREAD

**Issue by infotexture** [prettier/plugin-xml#2]
This plug-in currently strips all comments from XML files, but many projects use comments for licensing statements, documentation, or other mandatory information that must be preserved.

If the project prefers to remove comments by default, at least consider adding a configuration option that would allow users to preserve comments if necessary.

**Comment by kddeisz** [comment]
@infotexture definitely should! Could you potentially post a test case here? (An XML file with lots of comments would be ideal.)

**Comment by infotexture** [comment]
@kddeisz I don't have an extensively-commented file handy at the moment, but here's a [simple example from a real project](https://github.com/dita-ot/docs/blob/develop/topics/installing.ditamap):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<!--  This file is part of the DITA Open Toolkit project. See the accompanying LICENSE file for applicable license.  -->

<map>
  <title>Installing</title>

  <topicref keyref="prerequisite-software"/>
  <topicref keyref="determining-version-of-ditaot"/>
  <!-- ↓ branch-filter ↓ -->
  <topicref href="using-dita-command.dita"
            keys="first-build-using-dita-command" locktitle="yes">
    <topicmeta>
      <navtitle>Building output</navtitle>
    </topicmeta>
    <ditavalref href="../resources/novice.ditaval">
      <ditavalmeta>
        <dvrResourcePrefix>first-build-</dvrResourcePrefix>
      </ditavalmeta>
    </ditavalref>
  </topicref>
  <!-- ↑ end-filtering ↑ -->
  <topicref keyref="installing-via-homebrew"/>
</map>
```

In this case, the second and third comments are used to mark a section of the file that is [included by reference elsewhere](https://github.com/dita-ot/docs/blob/develop/reference/docs-dita-features.dita#L52).
