### ISSUE TITLE
XML prettification changes content of XML tags

### ISSUE THREAD

**Issue by muenzpraeger** [prettier/plugin-xml#22]
When the line width of a file is reached the plugin prettifies the XML as it would prettify for example HTML. But with XML it can actually lead to not only changed formatting, but also changed content.

For example we ran [here](https://github.com/trailheadapps/ebikes-lwc/issues/104#issuecomment-559805517) into the issue that the plugin added line breaks to a `boolean`, which is invalid.

**Comment by pozil** [comment]
Kind of related to Issue #24

**Comment by kddeisz** [comment]
It no longer changes the content of tags, since #39
