### ISSUE TITLE
Preserve XML processing instructions

### ISSUE THREAD

**Issue by infotexture** [prettier/plugin-xml#3]
This plug-in currently preserves the optional [XML declaration](https://www.w3.org/TR/xml/#NT-XMLDecl) on the first line of XML files, but strips any subsequent [processing instructions](https://www.w3.org/TR/xml/#sec-pi) from the rest of the file.

For example, in many XML workflows, `<?xml-model … ?>` processing instructions are used to provide validation support via schema languages like RELAX NG, W3C XML Schema, DTD and Schematron.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="project.rnc" type="application/relax-ng-compact-syntax"?>
<foo />
```

For more information, see http://www.w3.org/TR/xml-model/ and http://xml-model.info.

Other use cases may depend heavily on other (proprietary) processing instructions, so it would be best to provide an option to handle _all_ processing instructions, regardless of their content.

If the project prefers to remove processing instructions by default, at least consider adding a configuration option that would allow users to preserve them if necessary.

**Comment by infotexture** [comment]
> best to provide an option to handle _all_ processing instructions, regardless of their content

Looks like the implementation in #6 only handles [XML declarations](https://www.w3.org/TR/xml/#NT-XMLDecl) and `<?xml-model?>` processing instructions by searching for `?xml` or `?xml-model` on [Line 10 of src/parse.js](https://github.com/prettier/plugin-xml/blob/master/src/parse.js#L10), but it still strips all other processing instructions from the rest of the file.

Per the spec, regular [processing instructions](https://www.w3.org/TR/xml/#sec-pi) don't begin with `?xml` but might contain other combinations of characters, like `<?pagebreak?>` or 

```xml
<?oxy_delete author="Bob" timestamp="20191115T162115+0100" content="deleted words"?>
```

Since processing instructions are currently deleted, I suggest you re-open this issue.

It looks like the current code also inserts an extra space before the closing `?>` of [XML declarations](https://www.w3.org/TR/xml/#NT-XMLDecl) like it does before the closing slash in empty elements. 

While this is not exactly **wrong**, I think it's less common practice in most cases — but this is perhaps better treated as a separate issue.

**Comment by infotexture** [comment]
@kddeisz See previous [comment](https://github.com/prettier/plugin-xml/issues/3#issuecomment-554403810): 

> Since processing instructions are currently deleted, I suggest you re-open this issue.

**Comment by bd82** [comment]
The processing Instructions should appear in the Parser's output
So I guess it is just a matter of "printing" them.
- https://github.com/SAP/xml-tools/blob/master/packages/parser/lib/parser.js#L94

**Comment by bd82** [comment]
Although they are consumed as a single large token:
- https://github.com/SAP/xml-tools/blob/master/packages/parser/lib/lexer.js#L100-L103

We should probably properly parse their parts to allow for "pretty" re-printing.
Please open an issue in xml-tools repo if that is the case...

**Comment by kddeisz** [comment]
@infotexture this is working on v0.5.0. Are you having trouble with it?

**Comment by infotexture** [comment]
@kddeisz Yes, even in 0.6.0, processing instructions that don't start with `?xml` are still being dropped as described in my previous [comment](https://github.com/prettier/plugin-xml/issues/3#issuecomment-554403810). Tried with the sample PIs provided there:

```xml
<?pagebreak?>
```

```xml
<?oxy_delete author="Bob" timestamp="20191115T162115+0100" content="deleted words"?>
```

**Comment by kddeisz** [comment]
Ahh I didn't understand until I continued messing with it that you meant processing instructions inside of other elements as opposed to outside the root element. I've opened #50 to handle that.

**Comment by infotexture** [comment]
Thanks, your changes in https://github.com/prettier/plugin-xml/pull/50/commits/f38f07058e61e44943ca064b3fe40294a27353d7 for #50 did the trick. 🙇
