### ISSUE TITLE
How to install in VScode globally

### ISSUE THREAD

**Issue by stevenmay-dev** [prettier/plugin-xml#34]
I'm using VSCode for Salesforce Dev and using Prettier for formatting.

I only seem to be able to enable this xml plugin per VSCode project not globally. 

For each created VSCode project I have to:
>npm init
>npm install --save-dev prettier @prettier/plugin-xml

I just want to enable this plugin for all my VSCode projects.  How do I do this just once?

**Comment by PymZoR** [comment]
Installing the plugin globally (with `-g`) and setting the `prettier.prettierPath` configuration entry your system `prettier` path should work

**Comment by stevenmay-dev** [comment]
> Installing the plugin globally (with `-g`) and setting the `prettier.prettierPath` configuration entry your system `prettier` path should work

Thanks I'll give that a shot.

**Comment by ChazUK** [comment]
Is there not a way for the plugin to be accessible when installed locally to the project, so that files will format on save?
