### ISSUE TITLE
Single empty lines are collapsed

### ISSUE THREAD

**Issue by PymZoR** [prettier/plugin-xml#36]
Using version 0.3.0
## Before
```xml
<a>
        <b/>


        <c/>

        <d/>
</a>
```
## After
```xml
<a>
        <b/>
        <c/>
        <d/>
</a>
```

## Expected result
```xml
<a>
        <b/>
    
        <c/>

        <d/>
</a>
```
According to https://prettier.io/docs/en/rationale.html, the blank lines between the `b` and `c` tags should collapse into one blank line, while the blank line between the `c` and `d` tags should be preserved.

**Comment by kddeisz** [comment]
This is fixed by https://github.com/prettier/plugin-xml/pull/39
