### ISSUE TITLE
strict whitespaceSensitivity only for elements without child elements

### ISSUE THREAD

**Issue by sunnybyeon** [prettier/plugin-xml#363]
### tabWidth

4

### xmlWhitespaceSensitivity

ignore

### Input XML

```xml
<?xml version="1.0" encoding="UTF-8" ?><parent><childOne><childTwo attributeOne="valueOne" attributeTwo="valueTwo" attributeThree="valueThree">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, at dolore illo nesciunt</childTwo></childOne></parent>
```

### Current output XML

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<parent>
    <childOne>
        <childTwo
            attributeOne="valueOne"
            attributeTwo="valueTwo"
            attributeThree="valueThree"
        >
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam,
            at dolore illo nesciunt
        </childTwo>
    </childOne>
</parent>
```

### Expected output XML

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<parent>
    <childOne>
        <childTwo
            attributeOne="valueOne"
            attributeTwo="valueTwo"
            attributeThree="valueThree"
        >Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, at dolore illo nesciunt</childTwo>
    </childOne>
</parent>
```

**Comment by sunnybyeon** [comment]
Is it possible to use strict whitespaceSensitivity only for elements without child elements so I can get the expected output? I tried using ignore for xmlWhitespaceSensitivity with the printWidth to an extremely large number and it works quite fine but it doesn't break line with the attributes and I get a result like this.
`<?xml version="1.0" encoding="UTF-8" ?>
<parent>
    <childOne>
        <childTwo attributeOne="valueOne" attributeTwo="valueTwo" attributeThree="valueThree">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, at dolore illo nesciunt</childTwo>
    </childOne>
</parent>`

**Comment by kddnewton** [comment]
At the moment, there is not an option to make this happen. Unfortunately there are just too many permutations to really support every kind of option. If you need strict whitespace for only some elements, I would suggest looking at the ignore ranges in the README and using those.
