### ISSUE TITLE
Nested strings are broken apart

### ISSUE THREAD

**Issue by IanVS** [prettier/plugin-xml#37]
I tried this project out on some .xml test fixtures, and found that the first time I ran it, it made changes like:

![image](https://user-images.githubusercontent.com/4616705/72097591-b34b1600-32ea-11ea-97ed-e7e1fd5cf707.png)

And then if I ran it again, it would make even more changes:

![image](https://user-images.githubusercontent.com/4616705/72097612-bd6d1480-32ea-11ea-8ed2-d2ef8d722c57.png)

I believe it shouldn't have made any changes at all, since double quotes don't need to be escaped if they're inside single quotes.

**Comment by kddeisz** [comment]
This is all fixed up since #39
