### ISSUE TITLE
Randomly adds semi-colon at the end of inner text when using tage named <flow>

### ISSUE THREAD

**Issue by paustint** [prettier/plugin-xml#394]
### bracketSameLine

true

### printWidth

140

### xmlWhitespaceSensitivity

strict

### xmlSelfClosingSpace

true

### Input XML

```xml
<flow>Big_Deals_Total_Requests_Post</flow>
```

### Current output XML

```xml
<flow>
Big_Deals_Total_Requests_Post;
</flow>
```

### Expected output XML

```xml
<flow>Big_Deals_Total_Requests_Post</flow>
```

I have no idea why a semi-colon is getting added to the end of this text inside the tags. This has caused some breakage for a deployment to one of our systems. No other tags are impacted. This seems to be something magical with the `<flow>` tag, which is system generated and not something that we have control over.

**Comment by kddnewton** [comment]
You should use the `--embedded-language-formatting` option to turn off this behavior. It's because the tag is matching the name of an embedded prettier parser.
