### ISSUE TITLE
char < not working into string, but > is working

### ISSUE THREAD

**Issue by mathben** [prettier/plugin-xml#450]
### bracketSameLine

false

### xmlWhitespaceSensitivity

strict or ignore

### xmlSelfClosingSpace

true

### Error

NOT WORKING, got error "Error parsing XML"
```xml
<?xml version="1.0" encoding="utf-8"?>
<test>
<a b="c<d" />
</test>
```

WORKING

```xml
<?xml version="1.0" encoding="utf-8"?>
<test>
<a b="c>d" />
</test>
```

WORKING

```xml
<?xml version="1.0" encoding="utf-8"?>
<test>
<a b="c=d" />
</test>
```

**Comment by kddnewton** [comment]
I've reported this to the upstream parsing library that I'm using and will track it there: https://github.com/SAP/xml-tools/issues/383.

**Comment by kddnewton** [comment]
I'm reopening this because I want to have better error messages, but turns out `<` is not allowed in attributes as per the spec: https://www.w3.org/TR/xml/#ValueType.

**Comment by mathben** [comment]
Ok, I need to replace `>` by `&gt;` and `<` by `&lt;` in my code.
Will we support error message for `>` too?

**Comment by kddnewton** [comment]
> should be fine, you shouldn’t need to touch that. The < will need
escaping yeah.
