### ISSUE TITLE
Inconsistent formatting depending on initial state

### ISSUE THREAD

**Issue by PymZoR** [prettier/plugin-xml#46]
I came across those cases (not an exhaustive list though) on files where long lines and big tag attributes were exceeding the maximum line length. While formatting some of them by hand, I figured out that the formatting was actually quite different depending on the initial state. 

Prettier version : 1.19.1
Pretter options : 
```json
{
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "insertPragma": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "none",
  "useTabs": false,
  "parser": "xml"
}
```

###### Before
```xml
<a>
<b>
<c xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="1" yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy="2" zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz="3"/>
</b>
</a>
```
###### After
```xml
<a>
<b>
<c
      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="1"
      yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy="2"
      zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz="3"
    />
</b>
</a>
```
Here, the `b` tag is not indented, and the first half of `c` tag as well as his attributes are missing an indent.

###### Before
```xml
<a>
<b>
    <c xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="1" yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy="2" zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz="3"/>
</b>
</a>
```
###### After
```xml
<a>
<b>
    <c
      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="1"
      yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy="2"
      zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz="3"
    />
</b>
</a>
```
The `c` tag is correctly indented, `b` tag still isn't.

###### Before
```xml
<a><b><c xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="1" yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy="2" zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz="3"/></b></a>
```
###### After
```xml
<a><b><c
      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="1"
      yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy="2"
      zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz="3"
    /></b></a>

```
I don't really know what is going on on this one.

**Comment by kddeisz** [comment]
Yeah this is because in XML, whitespace is sensitive in every element unless otherwise specified by the schema. Try using `xmlWhitespaceSensitivity` to set `"ignore"`, that's probably what you want.
