### ISSUE TITLE
Indentation problem

### ISSUE THREAD

**Issue by nallarj** [prettier/plugin-xml#47]
I am trying to use the indentation. I have an problem :

```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<foo>
<bar>
baz
</bar>
<baz>
<plop />
</baz>
</foo>
```

if the balise contain other things than balise xml, for example here, "baz". the indentation is bad. my output : 

```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<foo>
    <bar>
baz
</bar>
    <baz>
        <plop />
    </baz>
</foo>
```

**Comment by CircleCode** [comment]
note: this is the output with the newly added `xmlWhitespaceSensitivity: ignore` option

**Comment by kddeisz** [comment]
Yeah at the moment even with the `ignore` option set it tries to respect whitespace inside nodes with mixed content. I suppose I can go whole hog on really ignoring whitespace for these kinds of node. I can take a look at doing that later.

**Comment by vinayhk1989** [comment]
any update on fixing the issue ?

**Comment by kddeisz** [comment]
I believe I've addressed this in https://github.com/prettier/plugin-xml/pull/103 which has been merged into master. Can someone on this issue (@nallarj, @CircleCode, @vinayhk1989) pull master and verify on their machine before I release a new version?

**Comment by kddeisz** [comment]
Alright I'm pretty comfortable saying this is fixed. Going to close this. Feel free to reopen if `v0.10.0` doesn't fix this for you.
