### ISSUE TITLE
Respect `max_line_length = off`

### ISSUE THREAD

**Issue by viceice** [prettier/plugin-xml#59]
This plugin does not respect my editorconfig setting.

works
```ini
[*.{csproj,targets,props}]
max_line_length = 260
```

does not work
```ini
[*.{csproj,targets,props}]
max_line_length = off
```

**Comment by kddeisz** [comment]
Hey there - sorry but that's not within the scope of this plugin. It sounds like a bug with either your editor or prettier itself. This plugin doesn't have anything that would parse that kind of file.

**Comment by viceice** [comment]
I've configured prettier to parse those files as xml:
```json
{
  "singleQuote": true,
  "trailingComma": "es5",
  "xmlWhitespaceSensitivity": "ignore",
  "overrides": [
    {
      "files": [
        "*.proj",
        "*.csproj",
        "*.props",
        "*.targets",
        "*.nuspec",
        "*.runsettings",
        "*.spdata",
        "*.resx",
        "*.config",
        "*.webpart",
        "*.feature",
        "*.package"
      ],
      "options": { "parser": "xml" }
    }
  ]
}

```

So the bug also occues on nomal xml files. So it is maybe a bug in prettier

**Comment by celluj34** [comment]
I am having the same problem with SVG files. I can't speak to `.targets` or `.props`, but `.csproj` and `.svg` files ARE xml, so I have instructed this plugin to format those.

**Comment by kddnewton** [comment]
Looks like prettier does not support the `off` option, per

https://github.com/josephfrazier/editorconfig-to-prettier/blob/06aa57780ffddfc62209fe3bdfce5339845c1c49/index.js#L49-L51

**Comment by viceice** [comment]
it's now supported and it changed a lot of my XML code inside markdown code fences 🥳
