### ISSUE TITLE
Failed to parse XML containing attributes with special characters

### ISSUE THREAD

**Issue by luisg123v** [prettier/plugin-xml#607]
### xmlWhitespaceSensitivity

strict

### Input XML

```xml
<?xml version="1.0" encoding="utf-8" ?>
<node attributeá="value" />
```

### Current output XML

```xml
[error] file.xml: Error: unexpected character: ->á<-
```

### Expected output XML

```xml
XML should be parsed, as the same XML is parsed correctly by lxml despite special characters:

>>> from lxml import objectify
>>> xml = objectify.fromstring('<node attributeá="value" />')
>>> xml.attrib
{'attributeá': 'value'}
>>>
```

**Comment by luisg123v** [comment]
CC @moylop260 @luistorresm

**Comment by kddnewton** [comment]
I've opened an issue on the upstream parser here: https://github.com/SAP/xml-tools/issues/407.

**Comment by kddnewton** [comment]
Closing this as it's being tracked over on that other issue. Sorry about this @luisg123v I'm at the mercy of the parser. If you feel like a contribution, that'd be a great place.

**Comment by luisg123v** [comment]
@kddnewton roger, I'll be following that other issue.

Thanks a lot.
