### ISSUE TITLE
[Feature Request] Support converting quotes (i.e. `singleQuote` setting)

### ISSUE THREAD

**Issue by celluj34** [prettier/plugin-xml#662]
Hello;

I am ultimately using Prettier within VSCode, but I have this plugin installed locally. I can see in the Prettier logs that my files are being touched, but the quotes aren't being converted even though it's detecting `singleQuote` as `false`.

Here are all the settings:

```json
{
  "filepath": "<etc>\\assets\\svg\\check-list.svg",
  "parser": "xml",
  "useTabs": false,
  "tabWidth": 2,
  "printWidth": 9999,
  "singleQuote": false,
  "xmlWhitespaceSensitivity": "ignore"
}
```

example input (shortened for brevity):

```xml
<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' version='1.1' viewBox='-10 0 2068 2048'>
  <g transform='matrix(1 0 0 -1 0 2048),rotate(0,1034,1024)'>
    <path fill='' d='M640 1152v128h1408v-128h-1408zM640' />
  </g>
</svg>
```

See `fill=''`, it's not getting converted to `fill=""`.

**Comment by kddnewton** [comment]
Ahh yeah. This isn't really a bug, so much as a feature request. You can see the plugin options that we support in the README, `singleQuotes` isn't listed as one of the options as the moment.

**Comment by starise** [comment]
I was looking exactly for this. It'd be a convenient feature to add.

**Comment by bweis** [comment]
Added support in #684 

Feel free to pull that down and test it in your project. @celluj34

**Comment by kddnewton** [comment]
Fixed by https://github.com/prettier/plugin-xml/pull/684
