### ISSUE TITLE
Inconsistent indentation for element with multi-line content

### ISSUE THREAD

**Issue by peve** [prettier/plugin-xml#666]
I have some xml elements with text content spread of multiple lines, see input below.

Is it possible get `prettier/plugin-xml` to format each line according to the desired `tabWidth`, `useTabs` etc? Currently it seems like it only formats the first line (`Hello` in the example) and the rest of the content is untouched.

**Input**
```
<test>
             Hello
	world
      !
</test>
```

**Desired output**
```
<test>
  Hello
  world
  !
</test>
```

**Actual output**
```
<test>
  Hello
	world
      !
</test>
```

**.prettierrc**
```
{
  "endOfLine": "crlf",
  "xmlWhitespaceSensitivity": "ignore"
}
```

**Comment by kddnewton** [comment]
Unfortunately there's really no way for us to know how you want that formatted. Consider:

```xml
<test>
list:
  - foo
  - bar
  - baz
</test>
```

You wouldn't expect a formatter to mess this up.
