### ISSUE TITLE
Negative zeros in XML file

### ISSUE THREAD

**Issue by jptuominen** [prettier/plugin-xml#675]
Hey,
I format a specific XML file with this tool. The file contains a block like this:

```
<element name="attr">
  <width>50%</width>
  <x>-0</x>
      <y>-0</y>
</element>
```
After formatting negative zeros become unsigned:

```
<element name="attr">
  <width>50%</width>
  <x>0</x>
  <y>0</y>
</element>
```
What causes this and could this behavior be ignored?
Thanks.

**Comment by kddnewton** [comment]
Oh no! That's definitely a bug. I'll take a look.

**Comment by kddnewton** [comment]
Interesting, I can't seem to reproduce this with the latest version. Can you try again?
