### ISSUE TITLE
It would be great to be able to sort XML tags within an XML file, useful for Salesforce XML metadata

### ISSUE THREAD

**Issue by RupertBarrow** [prettier/plugin-xml#681]
see https://github.com/swagup-com/sf-xml-formatter

**Comment by Airkro** [comment]
https://www.npmjs.com/package/prettier-plugin-sf-xml ?

**Comment by RupertBarrow** [comment]
Yes

**Comment by kddnewton** [comment]
Fixed by https://github.com/prettier/plugin-xml/pull/685
