### ISSUE TITLE
Not compatible wuth prettier 3

### ISSUE THREAD

**Issue by zdm** [prettier/plugin-xml#690]
Could you please release code, compatible with pretties 3?

**Comment by coliff** [comment]
was released 1 minute ago :-)

https://www.npmjs.com/package/@prettier/plugin-xml/v/3.0.0

**Comment by tylervz** [comment]
After upgrading this plugin to v3.1.0 and prettier to v3.0.0, I am getting errors when trying to format XML files.

The `.prettierrc.json` file for my project is the following:
```
{
  "singleQuote": false,
  "overrides": [
    {
      "files": ["*.xml"],
      "options": {
        "xmlWhitespaceSensitivity": "ignore"
      }
    }
  ]
}
```
When I run `./node_modules/.bin/prettier --write 'config.xml'` I get the following:
```
[warn] Ignored unknown option { xmlWhitespaceSensitivity: "ignore" }. Did you mean htmlWhitespaceSensitivity?
[error] No parser could be inferred for file "/Users/tylervanzanten/src/hypercision/rollcall/mobile/rollcall-mobile/config.xml".
```
I didn't notice this issue at first since I typically run `prettier --write .` and I did not see that prettier was skipping all the XML files in my project.

I am using Node v18.16.0.

**Comment by kddnewton** [comment]
@tylervz you need to specify the plugins in v3. See the CHANGELOG here: https://prettier.io/blog/2023/07/05/3.0.0.html#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker.

**Comment by kddnewton** [comment]
Or alternatively the documentation: https://prettier.io/docs/en/plugins.html#using-plugins

**Comment by fenuks** [comment]
It seems that the latest released version is still not compatible with prettier v3.

For

```sh
$ npm list -g --depth=0
/usr/local/lib
+-- @prettier/plugin-xml@3.2.0
+-- prettier@3.0.2
```

I get error:
```sh
$ prettier service/pmd.xml 
service/pmd.xml
[error] service/pmd.xml: Error: printer.embed has too many parameters. The API changed in Prettier v3. Please update your plugin. See https://prettier.io/docs/en/plugins.html#optional-embed
[error]     at printEmbeddedLanguages (file:///usr/local/lib/node_modules/prettier/index.mjs:17619:11)
[error]     at printAstToDoc (file:///usr/local/lib/node_modules/prettier/index.mjs:17750:9)
[error]     at async coreFormat (file:///usr/local/lib/node_modules/prettier/index.mjs:18061:14)
[error]     at async formatWithCursor (file:///usr/local/lib/node_modules/prettier/index.mjs:18259:14)
[error]     at async formatFiles (file:///usr/local/lib/node_modules/prettier/internal/cli.mjs:6800:18)
[error]     at async main (file:///usr/local/lib/node_modules/prettier/internal/cli.mjs:6992:5)
[error]     at async Module.run (file:///usr/local/lib/node_modules/prettier/internal/cli.mjs:6946:5)
```

**Comment by kddnewton** [comment]
@fenuks if you create a new project and run it, it should be working. Presumably your cache is out of date. Otherwise how would our CI work at all?
