### ISSUE TITLE
[Bug] "xmlQuoteAttributes" setting not inheriting from .editorconfig "quote_type" setting

### ISSUE THREAD

**Issue by celluj34** [prettier/plugin-xml#697]
I am using v3.1.0 of plugin-xml, and I was excited to use the new quote setting, but I see it's not using the value I have already set in my .editorconfig file for XML files. Is this intended? How can I eliminate setting this value twice in two files?

**Comment by bweis** [comment]
According to [the docs](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options) it looks like only a few properties are supported from the `.editorconfig`.

I would just add `xmlQuoteAttributes: "single" | "double" | "preserve"` to your `.prettierconfig`

**Comment by celluj34** [comment]
Yeah, that's what I've done for now, I was just hoping there was a way to not have to duplicate it.

Thanks!
