### ISSUE TITLE
Attribute values erased

### ISSUE THREAD

**Issue by bradchristensen** [prettier/plugin-xml#7]
When running `prettier --write .\app.config --parser=xml`, the following `app.config` file gets transformed from:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="MassTransitConcurrencyLimit" value="1" />
    <add key="MassTransitPrefetchCount" value="8" />
  </appSettings>
</configuration>
```

Into:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="MassTransitConcurrencyLimit" value="" />
    <add key="MassTransitPrefetchCount" value="" />
  </appSettings>
</configuration>
```

Losing each of the values `1` and `8` for the two appSettings.

The expected behaviour is that the file should remain unchanged from the initial state.

`prettier@1.19.1`
`@prettier/plugin-xml@0.2.0`

**Comment by kddeisz** [comment]
Sorry about that this is fixed on master and will be released momentarily.
