### ISSUE TITLE
Error "No parser could be inferred for file /*.xml" when execution the prettier plugin-xml

### ISSUE THREAD

**Issue by Kasde96** [prettier/plugin-xml#709]
Hallo there,

i want to use your prettier xml plugin but it doesn't work for me. I installed it as descriped in the read.me file.
Here is my package.json file:
![image](https://github.com/prettier/plugin-xml/assets/97966330/1a2c3fca-e801-48f2-8fef-450e5ea791ed)

Have i done something wrong?

Thanks

**Comment by coliff** [comment]
Be sure to have the `plugins:` set in your Prettier config. You'll want something like this:

```json
{
  "plugins": ["@prettier/plugin-xml"],
  "printWidth": 80,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true
}
```

**Comment by Kasde96** [comment]
Oh yes, that was my problem. I have added this in the `.pluginrc`. 
Thanks
