### ISSUE TITLE
Documentation update for prettier v3?

### ISSUE THREAD

**Issue by kyle-blair** [prettier/plugin-xml#714]
Before I open a pull request, I wanted to confirm that functionality is now slightly different from the current README.

I upgraded prettier to v3 and was getting the error:
`[error] No parser could be inferred for file "/path/to/xml/file.xml".`

I was able to fix this by adding the following plugin section to my `.prettierrc` file:
```json
    "plugins": ["@prettier/plugin-xml"]
```

This wasn't entirely obvious anywhere in the documentation either here or in the main prettier repo. I think it would be useful to mention here now that plugin search has been disabled in prettier v3?

**Comment by kddnewton** [comment]
Fixes on main
