### ISSUE TITLE
Formatting not working on Salesforce xml files

### ISSUE THREAD

**Issue by Renan-Mastropaolo** [prettier/plugin-xml#741]
Hello,

I've been trying to format my Salesforce metadata xml files (Profiles, Permission Sets, etc...) but it is not working as expected.
The only output I got is to add an extra space on the first line of each file:
Input:
```
<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
         <applicationVisibilities>


        <application>Example</application>
        <default>false</default>
        <visible>true</visible>
         </applicationVisibilities>
        <applicationVisibilities>
        <application>Example</application>
        <default>false</default>
        <visible>true</visible>
        </applicationVisibilities>
    <customPermissions>
                <enabled>true</enabled>
        <name>Example</name>
    </customPermissions>
</Profile>
```

Output:
```
<?xml version="1.0" encoding="UTF-8"? >
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
         <applicationVisibilities>


        <application>Example</application>
        <default>false</default>
        <visible>true</visible>
         </applicationVisibilities>
        <applicationVisibilities>
        <application>Example</application>
        <default>false</default>
        <visible>true</visible>
        </applicationVisibilities>
    <customPermissions>
                <enabled>true</enabled>
        <name>Example</name>
    </customPermissions>
</Profile>
```

### Prettier config file
{
  "plugins": ["@prettier/plugin-xml"],
  "printWidth": 1000000,
  "tabWidth": 4,
  "trailingComma": "none",
  "bracketSameLine": true,
  "xmlSortAttributesByKey": true
}

### Package.json
{
    "name": "Test",
    "description": "test",
    "devDependencies": {
        "@prettier/plugin-xml": "3.2.2",
        "prettier": "3.1.0"
    }
}

### Command used to trigger the plugin
./node_modules/.bin/prettier -w "force-app/main/default/permissionsets/"

Is there something that I am missing?

Thank you for your help.

**Comment by kddnewton** [comment]
https://github.com/prettier/plugin-xml#whitespace

**Comment by Renan-Mastropaolo** [comment]
Thank you, I misunderstood that part. But the extra line breaks inside the xml tags were not removed, is that intentional?

**Comment by kddnewton** [comment]
If its strict, we don't remove any semantically relevant whitespace, yeah
