### ISSUE TITLE
Preserve whitespace in empty `<xsl:text>` nodes

### ISSUE THREAD

**Issue by infotexture** [prettier/plugin-xml#748]
In #635, the `xmlWhitespaceSensitivity` option was extended with the `preserve` suboption to preserve significant whitespace within text nodes for #478.

This works fine in `<xsl:text>` nodes, as long as they contain text content. For example, the space here is preserved as expected in `preserve` mode:

```xml
    <xsl:text>slide </xsl:text>
```

— and stripped (as expected) in `ignore` mode:

```diff
-   <xsl:text>slide </xsl:text>
+   <xsl:text>slide</xsl:text>
```

However, if `<xsl:text>` nodes do **not** contain text content, even `preserve` mode treats them as empty nodes and collapses them — but the whitespace here is significant in some cases.

For example, this syntax might be used in a stylesheet to define a newline character:

```diff
  <xsl:variable name="newline">
- <xsl:text>
- </xsl:text>
+   <xsl:text/>
  </xsl:variable>
```

After this change, the newline character would be lost.

In other cases, a single space within `<xsl:text>` nodes may be used when constructing sequences of HTML class attribute values, or similar constructs. Without the space, values would be concatenated to a single keyword, instead of separated with spaces:

```diff
  <xsl:template match="@*" mode="serialize">
-   <xsl:text> </xsl:text>
+   <xsl:text/>
    <xsl:value-of select="name()"/>
    <xsl:text>="</xsl:text>
    <xsl:value-of select="."/>
    <xsl:text>"</xsl:text>
  </xsl:template>

```

cc/ @kendrickw

**Comment by kddnewton** [comment]
@infotexture do you think we should preserve the space even in `ignore` mode? It seems like maybe we should.

**Comment by infotexture** [comment]
@kddnewton 🤔 Not sure about that.

I certainly _expected_ it to be preserved in `preserve` mode, and wasn't _surprised_ to see it ignored in `ignore` mode.

Since the whole point of the `<xsl:text>` element is to write parsable character data and  literal text to the output tree, it might make sense to preserve it even in `ignore` mode.

I'm not sure if there are any circumstances where that would be outright **wrong** — apart from the potential confusion that might be caused by not actually _ignoring_ something in `ignore` mode.

**Comment by stefan-jung** [comment]
@infotexture, to create a newline char, you might want to better use instead of:

```xml
<xsl:variable name="newline">
<xsl:text>
</xsl:text>
</xsl:variable>
```

This **`<variable>`**:

```xml
<xsl:variable name="newline" select="'&#xa;'"/>
```
