### ISSUE TITLE
Plugin is overwriting tag content

### ISSUE THREAD

**Issue by chivalry** [prettier/plugin-xml#751]
I'm working with a team of Salesforce developers that periodically creates salesforce metadata on our servers, and then retrieve that metadata into our local repositories. We have `husky` triggers that automatically run `prettier` as a `precommit` action. Recently we noticed that the XML plugin (I assume) is re-writing the tag contents such that it becomes incorrect and we're then unable to push the source code to our servers because of this.

Specifically,, we begin with markup like the following:

```
    <flowAccesses>
        <enabled>true</enabled>
        <flow>Mock_Case_Screen_Flow</flow>
    </flowAccesses>
    <flowAccesses>
        <enabled>true</enabled>
        <flow>Mock_Create_Case_Flow</flow>
    </flowAccesses>
    <flowAccesses>
        <enabled>true</enabled>
        <flow>Mock_Object_Link_Flow</flow>
    </flowAccesses>
```

When we commit (or manually make a change and save the file, which also triggers `prettier`), the above gets converted to this:

```
    <flowAccesses>
        <enabled>true</enabled>
        <flow>
Mock_Case_Screen_Flow;
        </flow>
    </flowAccesses>
    <flowAccesses>
        <enabled>true</enabled>
        <flow>
Mock_Create_Case_Flow;
        </flow>
    </flowAccesses>
    <flowAccesses>
        <enabled>true</enabled>
        <flow>
Mock_Object_Link_Flow;
        </flow>
    </flowAccesses>
```

When we try to push this code to our servers, we're given errors that, for example, `Mock_Case_Screen_Flow;` doesn't exist.

Our current workarounds are to add XML files to our `.prettierignore` or to bypass the `husky` trigger with `--no-verify` during commit.

Note that this is _only_ happening with the `flow` tag. No other tags in this particular XML file, which is about 350 lines long, are affected.

**Comment by kddnewton** [comment]
That's happening because `flow` matches an existing prettier plugin, which switches to that formatter. Turn off https://prettier.io/docs/en/options.html#embedded-language-formatting.
