### ISSUE TITLE
Extension `Prettier - code formatter` is configured as formatter but it cannot format 'edmx'-files 

### ISSUE THREAD

**Issue by aspirio187** [prettier/plugin-xml#758]
Hi,

Since the update to version 3 of prettier, xml files cannot be formatted anymore. The configuration file contains the plugin `@prettier/plugin-xml` and when formatting JavaScript files, it will correctly retrieve the whole prettier configuration 

```shell
{
  "filepath": "/home/[USER]/[FOLDER_1]/[FOLDER_2]/[FOLDER_3]/Home.controller.js",
  "parser": "babel",
  "printWidth": 120,
  "tabWidth": 2,
  "bracketSameLine": true,
  "singleQuote": true,
  "semi": false,
  "trailingComma": "all",
  "xmlWhitespaceSensitivity": "ignore",
  "xmlSelfClosingSpace": true,
  "singleAttributePerLine": true,
  "quoteProps": "as-needed",
  "plugins": [
    "/[APP_FOLDERS]/node_modules/@prettier/plugin-xml/src/plugin.js"
  ]
}
```

But as soon as you try to format an XML file, you get the following: 

![image](https://github.com/prettier/plugin-xml/assets/56565073/fae8e6c3-0cac-41ee-924b-0ab29c0939a2)

It is possible to use the command `npx prettier --write . --plugin=@prettier/plugin-xml` or `node_modules/prettier/bin/prettier.cjs --write . --plugin=@prettier/plugin-xml`. This will successfully read all XML files and format them if needed.

I use **Visual Studio Code** with Prettier version **3.2.4** and plugin-xml version **3.2.2**

**Comment by kddnewton** [comment]
We switched to using https://github.com/ikatyang/linguist-languages to house the official list of files for XML. We use a preprocessing step to pull in their latest updates for XML files. You can either open an issue there to get it listed, or you can use the `overrides` configuration option to ensure your edmx files are formatted using the XML plugin.
