### ISSUE TITLE
Prettier doesn't detect at all

### ISSUE THREAD

**Issue by pyj-pd** [prettier/plugin-xml#760]
This is my `prettier.config.js` config file.
```js
/** @type {import("prettier").Config} */
module.exports = {
  plugins: ['@prettier/plugin-xml'],

  tabWidth: 2,
  useTabs: false,
  arrowParens: 'always',
  bracketSameLine: false,
  bracketSpacing: true,
  endOfLine: 'lf',
  jsxSingleQuote: false,
  semi: false,
  singleAttributePerLine: true,
  singleQuote: true,

  overrides: [
    {
      files: ['*.xml'],
      options: {
        xmlQuoteAttributes: 'double',
        xmlSelfClosingSpace: true,
        xmlSortAttributesByKey: false,
        xmlWhitespaceSensitivity: 'strict',
      },
    },
  ],
}
```

And I tried to format the file with this following command:
```bash
$ pnpm exec prettier --write data.xml --plugin=@prettier/plugin-xml --config=./prettier.config.js
data.xml 12ms (unchanged)
```

It doesn't change the file at all, and it seems not to detect the file as well in VSCode too.
![Prettier in VSCode showing not-supported icon](https://github.com/prettier/plugin-xml/assets/123401626/5027e5b9-a251-415a-bb70-0ff96305f937)

I also have the package installed successfully as well.

**Comment by pyj-pd** [comment]
I will close this issue as my project doesn't need XML now.

**Comment by kddnewton** [comment]
I think you want an `s` on `--plugins=`
