### ISSUE TITLE
Chokes on doctype with custom entities

### ISSUE THREAD

**Issue by PieterVanEde** [prettier/plugin-xml#774]
In our repo the parser chokes on a SVG with custom elements. This seems regular in Adobe Illustrator. As the files are provided to use, we cannot change the export options (that you would normally do). But aside from that, this is valid xml which should be handled by this parser.

The offending SVG is attached below. Btw, great work on this plugin, it is really helpful!

![land_rover](https://github.com/prettier/plugin-xml/assets/53824129/487c46f4-4d59-4a86-b4da-771fab6f5e92)

**Comment by kddnewton** [comment]
Yeah unfortunately this is a limitation of the parser we're using. The issue is here: https://github.com/SAP/xml-tools/issues/450. I'm still waiting on them to fix this.

**Comment by PieterVanEde** [comment]
That's too bad! I realize it's quite a piece of work, but maybe another xml parser is a solution?

**Comment by kddnewton** [comment]
I would happily accept a PR if you're offering!
