### ISSUE TITLE
Changes Content

### ISSUE THREAD

**Issue by ntotten** [prettier/plugin-xml#8]
When running this on an attribute like:

```
<apiVersion>47.0</apiVersion>
```

The output is:

```
<apiVersion>47</apiVersion>
```

This specifically is used for Salesforce metadata in which case this is a breaking change.  Not sure if this is considered a valid XML optimization, but if so, i think we need an option to disable this. My opinion though is that contents are never modified.

Thanks! Great project so far. :)

**Comment by takahitomiyamoto** [comment]
@ntotten Thank you. I will close my issue because of duplication.
https://github.com/prettier/plugin-xml/issues/9

**Comment by ntotten** [comment]
@takahitomiyamoto Oh sorry, i didn't see that. Thanks!

**Comment by kddeisz** [comment]
Sorry about that, this is fixed on master and will be released soon.
