### ISSUE TITLE
Also recognize .wsdl files?

### ISSUE THREAD

**Issue by cavo789** [prettier/plugin-xml#89]
Hello

The plugin works pretty good with `.xml` files (i.e. with the `.xml` file extension).

Is it possible to associate other extensions like `.wsdl` to the xml plugin?  (For info, a WSDL file is the manifest of a web service; this is a specialized XML content)

The following command will return this error `[error] No parser could be inferred for file: webservice.wsdl`

```bash
prettier.cmd --write "**/*.wsdl"
```

Thanks

**Comment by kddeisz** [comment]
@cavo789 sorry this took so long! This is released as part of v0.8.0.

**Comment by cavo789** [comment]
Don't excuse yourself Kevin... Many thanks for your work and improvements !!!
